apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  annotations:
    apps.open-cluster-management.io/git-branch: master
    apps.open-cluster-management.io/git-path: clusters/thor
    apps.open-cluster-management.io/reconcile-option: merge
  labels:
    app: cluster-thor
  name: cluster-thor-subscription-1
  namespace: hcpclusters
spec:
  channel: hcpclusters/hcprepository
  placement:
    placementRef:
      kind: PlacementRule
      name: hcp-bootstrap-placement-1
---
apiVersion: app.k8s.io/v1beta1
kind: Application
metadata:
  name: cluster-thor-hcp-home-lab
  namespace: hcpclusters
spec:
  componentKinds:
  - group: apps.open-cluster-management.io
    kind: Subscription
  descriptor: {}
  selector:
    matchExpressions:
      - key: app
        operator: In
        values: 
          - cluster-thor-hcp-home-lab      
